# cargo-features = ["consts-generics"]

[package]
name = "lustre_analyzer"
version = "0.1.0"
edition = "2024"

[dependencies]
nom = "8"
indexmap = "2.12.0"
nom-language= "0.1.0"
nom_locate = "5.0.0"
lsp-types = "0.97.0" 

colored = "3"
